import axios from "axios";
import type { NextPage } from "next";
import Head from "next/head";
import { useEffect } from "react";
import Header from "../components/Header/Header";
import Nav from "../components/Nav/Nav";
import Results from "../components/Results/Results";
import requests from "../utils/requests";

export interface IApiResponseProps {
  data: any;
  status: number;
}

const Home: NextPage = ({ data }: any) => {
  return (
    <div>
      <Head>
        <title>Hulu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Nav />
      <Results results={data?.results || []} />
    </div>
  );
};

export async function getServerSideProps(
  context: any
): Promise<{ props: IApiResponseProps }> {
  const genre = context.query["genre"] as keyof typeof requests;
  const response = await axios.get(
    `https://api.themoviedb.org/3${
      requests[genre]?.url || requests.fetchTrending.url
    }`
  );
  const response2 = await axios.get(
    "https://api.themoviedb.org/3/genre/movie/list?api_key=0842f8a7716bb1ea81b0e74d55092196&language=en-US"
  );
  return { props: { data: response.data, status: response.status } };
}

export default Home;
